apiVersion: apps/v1
kind: Deployment
metadata:
  name: ufotracker-app
  namespace: ufology
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ufotracker-app
  template:
    metadata:
      labels:
        app: ufotracker-app
    spec:
      containers:
        - name: ufotracker
          image: luananascimento/ufotracker-app:latest
          env:
            - name: POSTGRES_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: POSTGRES_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_PASSWORD
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_NAME
            - name: SPRING_DATA_REDIS_HOST
              value: "redis-service"
            - name: SPRING_DATA_REDIS_PORT
              value: "6739"