apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-cache
  namespace: ufology
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-cache
  template:
    metadata:
      labels:
        app: redis-cache
    spec:
      containers:
        - name: redis
          image: redis:alpine
          ports:
            - containerPort: 6739