name: Secret Demo
on: [ push ]
jobs:
  show-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Verificar API_KEY
        run: |
          if [ -n "{{secrets.API_KEY}}" ]; then
            echo "API_KEY está configurada"
            else
            echo "API_KEY não está configurada"
          fi